"""add machine command system

Revision ID: a631c499ce92
Revises: 
Create Date: 2026-08-22 18:07:15.263095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a631c499ce92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_command_id'), 'commands', ['command_id'], unique=True)
    op.create_index(op.f('ix_commands_id'), 'commands', ['id'], unique=False)
    op.create_index(op.f('ix_commands_machine_id'), 'commands', ['machine_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('process_state', sa.String(), nullable=True),
    sa.Column('auto_running', sa.Boolean(), nullable=True),
    sa.Column('emergency_stop', sa.Boolean(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('target_temperature', sa.Float(), nullable=True),
    sa.Column('cool_temperature', sa.Float(), nullable=True),
    sa.Column('hysteresis', sa.Float(), nullable=True),
    sa.Column('hold_time_minutes', sa.Integer(), nullable=True),
    sa.Column('heater', sa.Boolean(), nullable=True),
    sa.Column('stirrer', sa.Boolean(), nullable=True),
    sa.Column('cooler', sa.Boolean(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('power_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_machine_id'), 'machines', ['machine_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_machine_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_commands_machine_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_command_id'), table_name='commands')
    op.drop_table('commands')
    # ### end Alembic commands ###
